name: "phpcov"
description: "GitHub Action to turbocharge phpunit code coverage reports."
inputs:
  min_coverage:
    default: 50
    required: true
  now_project:
    default: null
    required: true
  now_token:
    required: true
  phpunit:
    default: "./vendor/bin/phpunit"
    required: true
outputs:
  url:
    description: ""
runs:
  using: "node12"
  main: "dist/index.js"
