on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: laravel/laravel
        path: laravel
    - id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - uses: shivammathur/setup-php@master
      with:
        coverage: pcov
        php-version: '7.4'
        extension: dom, fileinfo, mbstring
    - run: |
        composer install --no-suggest --prefer-dist --optimize-autoloader
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate
    - uses: ./
      id: phpcov
      with:
        path: laravel
        now_token: ${{ secrets.NOW_TOKEN }}
        now_project: "action-phpcov-${{ github.ref }}"
    - run: curl "${{ steps.phpcov.outputs.url }}"
